"""
Counterbalanced trial schedule for the SonoAdapt notification study.
NEW DESIGN – 2 Scenarios × 3 Systems × 2 Urgency = 12 Trials per participant.

Design
------
Within-subject:

  Scenarios : Interview (I), Mathe (M)
  Systems   : Baseline-Earcon (E), Baseline-Speech (S), SonoAdapt (A)
  Urgency   : LOW (L), HIGH (H)

6 conditions per scenario block:
  LE = LOW  + Baseline-Earcon
  HE = HIGH + Baseline-Earcon
  LS = LOW  + Baseline-Speech
  HS = HIGH + Baseline-Speech
  LX = LOW  + SonoAdapt
  HX = HIGH + SonoAdapt

Because every participant runs 6 LOW and 6 HIGH trials, and there are exactly
6 LOW and 6 HIGH messages, every message is seen exactly once per participant.

Block structure (6×6)
---------------------
  Odd  participants (1, 3, 5, …): Block 1 = Interview, Block 2 = Mathe
  Even participants (2, 4, 6, …): Block 1 = Mathe,     Block 2 = Interview

Within each 6-trial block, the order of the 6 conditions is counterbalanced
using a Williams Square of order 6 (balanced for position AND first-order
carry-over). Each participant receives two *different* rows of the square
(offset by 3 so rows 0↔3, 1↔4, 2↔5 are always paired).

Counterbalancing layers
-----------------------
1) Scenario order      : 2 permutations, alternated by odd/even participant ID.
2) Condition order     : Williams square of order 6 (balanced for first-order
                         carry-over). Each participant gets 2 different rows
                         (block1_row = (p-1)%6, block2_row = (block1_row+3)%6).
3) Message assignment  : The 6 LOW slots of a participant are the 6 cells
                         (scenario I/M) × (system E/S/A). A Williams square of
                         order 6 maps messages onto these canonical slots, with a
                         row index decoupled from the condition-order index, so
                         message × scenario and message × system are balanced.

Full balance is reached at multiples of N = 6 participants (LCM of 2, 6, 6).
Recommendation: N = 12 or 24.

Code format
-----------
  <Scenario I|M><System E|S|X><Urgency L|H><Message 1..6>
  e.g. IEL3 = Interview / Baseline-Earcon / LOW / Message L3 (Anna)
       MSH4 = Mathe     / Baseline-Speech  / HIGH / Message H4 (Paul)
       IXL1 = Interview / SonoAdapt        / LOW  / Message L1 (Lilly)
"""

import csv
import os
from collections import Counter, defaultdict

N_PARTICIPANTS = 24        # 4 full cycles of 6; use multiples of 6

OUT = os.path.dirname(os.path.abspath(__file__))

SCENARIOS = {
    "Interview": "I",
    "Mathe": "M",
}
SCENARIO_LIST = ["Interview", "Mathe"]   # canonical order used for message slots

# 6 conditions indexed 1–6
CONDITIONS = {
    1: ("LOW",  "Baseline-Earcon"),
    2: ("HIGH", "Baseline-Earcon"),
    3: ("LOW",  "Baseline-Speech"),
    4: ("HIGH", "Baseline-Speech"),
    5: ("LOW",  "SonoAdapt"),
    6: ("HIGH", "SonoAdapt"),
}

SYSTEM_CODE = {
    "Baseline-Earcon": "E",
    "Baseline-Speech": "S",
    "SonoAdapt":       "X",
}

# Williams square of order 6 – first row is the classical seed 1 2 6 3 5 4,
# subsequent rows generated by adding 1 (mod 6).
# Each ordered pair (predecessor→successor) appears exactly once across all 6 rows
# → first-order carry-over fully balanced.
W6_ROW1 = [1, 2, 6, 3, 5, 4]
W6 = [[(( v - 1 + k) % 6) + 1 for v in W6_ROW1] for k in range(6)]

# Canonical LOW / HIGH slots (fixed order, independent of scenario presentation order).
# Used to map W6 message rows onto (scenario, system) cells.
CANONICAL_SLOTS = [
    ("Interview", "Baseline-Earcon"),
    ("Interview", "Baseline-Speech"),
    ("Interview", "SonoAdapt"),
    ("Mathe",     "Baseline-Earcon"),
    ("Mathe",     "Baseline-Speech"),
    ("Mathe",     "SonoAdapt"),
]

LOW_MSG = {
    1: "New WhatsApp from Lilly: I went for a short walk after work yesterday.",
    2: "New WhatsApp from Max: I had pasta for dinner yesterday.",
    3: "New WhatsApp from Anna: I watched a documentary yesterday.",
    4: "New WhatsApp from Ben: I took the bus to work yesterday.",
    5: "New WhatsApp from Emma: I stopped by a bakery after work yesterday.",
    6: "New WhatsApp from Tom: I finished a book I was reading yesterday.",
}

HIGH_MSG = {
    1: "New WhatsApp from Sarah: I was in a bike accident. Can you call me right now?",
    2: "New WhatsApp from Leo: The fire alarm is going off in your apartment. Can you check?",
    3: "New WhatsApp from Laura: I think I forgot to turn the stove off. Can you check?",
    4: "New WhatsApp from Paul: I forgot my keys. Can you come downstairs and open the door?",
    5: "New WhatsApp from Sophie: I'm outside your building now. Can you come down?",
    6: "New WhatsApp from David: I think I left my wallet on the train. Can you call me right away?",
}


def build(n_participants=N_PARTICIPANTS):
    rows = []
    for p in range(1, n_participants + 1):
        # --- 1) Scenario order: odd = Interview first, even = Mathe first ---
        if (p - 1) % 2 == 0:
            scenario_order = ["Interview", "Mathe"]
        else:
            scenario_order = ["Mathe", "Interview"]

        # --- 2) Condition rows: block1 and block2 always different (offset +3) ---
        block1_row = (p - 1) % 6
        block2_row = (block1_row + 3) % 6
        cond_rows = [W6[block1_row], W6[block2_row]]

        # --- 3) Message assignment (decoupled from condition-order index) ---
        mrow = (p - 1 + (p - 1) // 6) % 6
        low_row  = W6[mrow]
        high_row = W6[(mrow + 3) % 6]
        low_map  = {slot: low_row[j]  for j, slot in enumerate(CANONICAL_SLOTS)}
        high_map = {slot: high_row[j] for j, slot in enumerate(CANONICAL_SLOTS)}

        trial = 0
        for block_pos, scenario in enumerate(scenario_order, start=1):
            cond_seq = cond_rows[block_pos - 1]
            for cpos, cond_idx in enumerate(cond_seq, start=1):
                trial += 1
                urgency, system = CONDITIONS[cond_idx]
                slot = (scenario, system)
                if urgency == "LOW":
                    mnum  = low_map[slot]
                    mid   = f"L{mnum}"
                    mtext = LOW_MSG[mnum]
                else:
                    mnum  = high_map[slot]
                    mid   = f"H{mnum}"
                    mtext = HIGH_MSG[mnum]

                code = (
                    f"{SCENARIOS[scenario]}"
                    f"{SYSTEM_CODE[system]}"
                    f"{'L' if urgency == 'LOW' else 'H'}"
                    f"{mnum}"
                )
                rows.append({
                    "participant":          p,
                    "block":                trial,          # Qualtrics block 1..12
                    "scenario_block":       block_pos,      # 1 or 2
                    "trial_in_scenario":    cpos,           # 1..6
                    "scenario":             scenario,
                    "system":               system,
                    "urgency":              urgency,
                    "condition_idx":        cond_idx,       # 1..6 (internal reference)
                    "message_id":           mid,
                    "code":                 code,
                    "message_text":         mtext,
                })
    return rows


# ---------------------------------------------------------------------------
# CSV writers
# ---------------------------------------------------------------------------

def write_long(rows, out=OUT):
    path = os.path.join(out, "design_long.csv")
    fields = list(rows[0].keys())
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=fields, delimiter=";")
        w.writeheader()
        w.writerows(rows)
    return path


def write_wide(rows, out=OUT):
    path = os.path.join(out, "design_wide.csv")
    by_p = defaultdict(dict)
    for r in rows:
        by_p[r["participant"]][r["block"]] = r["code"]
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f, delimiter=";")
        w.writerow(["participant"] + [f"B{i:02d}" for i in range(1, 13)])
        for p in sorted(by_p):
            w.writerow([p] + [by_p[p][i] for i in range(1, 13)])
    return path


def write_runsheets(rows, out=OUT):
    path = os.path.join(out, "runsheets.md")
    by_p = defaultdict(list)
    for r in rows:
        by_p[r["participant"]].append(r)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Run sheets – SonoAdapt Summative Study (one table per participant)\n\n")
        f.write(
            "Code format: `<scenario I|M><system E|S|A><urgency L|H><message 1-6>`  "
            "e.g. `MSH4` = Mathe / Baseline-Speech / HIGH / message H4.\n\n"
            "Systems: **E** = Baseline-Earcon, **S** = Baseline-Speech, **A** = SonoAdapt\n\n"
        )
        for p in sorted(by_p):
            f.write(f"## Participant {p:02d}\n\n")
            f.write("| Block | Code | Scenario | System | Urgency | Msg | Message text |\n")
            f.write("|---|---|---|---|---|---|---|\n")
            for r in by_p[p]:
                f.write(
                    f"| {r['block']} | `{r['code']}` | {r['scenario']} | {r['system']} | "
                    f"{r['urgency']} | {r['message_id']} | {r['message_text']} |\n"
                )
            f.write("\n")
    return path


# ---------------------------------------------------------------------------
# Balance checks
# ---------------------------------------------------------------------------

def checks(rows, n):
    sub = [r for r in rows if r["participant"] <= n]
    print(f"\n=== Balance checks for the first {n} participants ({len(sub)} trials) ===")

    c = Counter((r["scenario"], r["scenario_block"]) for r in sub)
    print("Scenario × block-position (each cell should be equal):",
          sorted(Counter(c.values()).items()))

    c = Counter((r["condition_idx"], r["trial_in_scenario"]) for r in sub)
    print("Condition × position-within-scenario:",
          sorted(Counter(c.values()).items()))

    c = Counter((r["condition_idx"], r["block"]) for r in sub)
    print("Condition × global block:",
          sorted(Counter(c.values()).items()))

    c = Counter((r["message_id"], r["system"]) for r in sub)
    print("Message × system:", sorted(Counter(c.values()).items()))

    c = Counter((r["message_id"], r["scenario"]) for r in sub)
    print("Message × scenario:", sorted(Counter(c.values()).items()))

    c = Counter((r["message_id"], r["trial_in_scenario"]) for r in sub)
    print("Message × position-within-scenario:",
          sorted(Counter(c.values()).items()))

    # Every message exactly once per participant
    bad = [p for p in {r["participant"] for r in sub}
           if len({r["message_id"] for r in sub if r["participant"] == p}) != 12]
    print("Participants with a repeated/missing message:", bad or "none")

    # Different condition rows in each of the 2 scenario blocks
    bad = []
    for p in sorted({r["participant"] for r in sub}):
        seqs = set()
        for bp in (1, 2):
            seqs.add(tuple(
                r["condition_idx"] for r in sub
                if r["participant"] == p and r["scenario_block"] == bp
            ))
        if len(seqs) != 2:
            bad.append(p)
    print("Participants with identical condition order in both blocks:", bad or "none")

    # First-order carry-over balance inside scenario blocks
    pairs = Counter()
    for p in sorted({r["participant"] for r in sub}):
        for bp in (1, 2):
            seq = [r["condition_idx"] for r in sub
                   if r["participant"] == p and r["scenario_block"] == bp]
            pairs.update(zip(seq, seq[1:]))
    print("Distinct ordered condition pairs observed:", len(pairs),
          "| counts:", sorted(set(pairs.values())))

    print("Unique codes used overall:", len({r["code"] for r in sub}))


if __name__ == "__main__":
    rows = build()
    print("wrote", write_long(rows))
    print("wrote", write_wide(rows))
    print("wrote", write_runsheets(rows))
    for n in (6, 12, 24):
        checks(rows, n)
